version: '3'

services:
  app:
    build: .
    image: shizheng-app
    restart: unless-stopped
    container_name: shizheng-app
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://postgres:123321@postgres:5432/shizheng
    depends_on:
      - postgres
      - redis
    networks:
      - shizheng_network
      - nginx-proxy-manager-network

  postgres:
    image: ankane/pgvector
    container_name: shizheng-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: shizheng
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shizheng_network

  redis:
    image: redis:latest
    container_name: shizheng-redis
    volumes:
      - redis_data:/data
    networks:
      - shizheng_network

networks:
  shizheng_network:
    driver: bridge
  nginx-proxy-manager-network:
    external: true

volumes:
  pgdata:
  redis_data:
