version: '3'

services:
  postgres:
    image: ankane/pgvector
    container_name: shizheng-postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: shizheng
    volumes:
      - ./pgdata:/var/lib/postgresql/data:rw
    networks:
      - shizheng_network

  redis:
    image: redis:latest
    container_name: shizheng-redis
    ports:
      - '6381:6379'
    volumes:
      - ./redis_data:/data
    networks:
      - shizheng_network

networks:
  shizheng_network:
    driver: bridge
